version: '3.8'  # Specify Docker Compose version

services:
  backend:          # First service: Go web application
    build: backend
    ports:
      - "8080:8080"  # Map host port 8080 to container port 8080
    depends_on:
      - db    # Ensure database starts before app
    environment:
      - DB_HOST=db        # Database hostname (service name)
      - DB_PORT=5432      # PostgreSQL default port
      - DB_USER=postgres  # Database username
      - DB_PASSWORD=postgres  # Database password
      - DB_NAME=postgres      # Database name

  db:          # Second service: PostgreSQL database
    image: postgres:15  # Official PostgreSQL image
    environment:
      - POSTGRES_USER=postgres        # DB username
      - POSTGRES_PASSWORD=postgres  # DB password
      - POSTGRES_DB=postgres             # DB name
    volumes:
      - db-data:/var/lib/postgresql/data  # Persistent storage
    ports:
      - "5432:5432"  # Optional: expose DB port to host

volumes:
  db-data:  # Named volume for database persistence